name: nextSurvival
author: nextRound
main: de.nextround.nextsurvival.nextSurvival
version: 1.1
api-version: 1.21.1

commands:
  home:
    description: Teleports the player to the set home location.
  sethome:
    description: Set's the home position for the player.
  prefix:
    description: Create a prefix for a specific player.
  back:
    description: Teleports the player back to the last death location.